data:
  path: /path/to/data/folder/

submissions:
  save: Yes  # If Yes, submissions and associated config file are saved at the given path.
  path: /path/to/submission/folder/

kernels:
  kernel: onehot # in ["onehot", "spectrum"]
  type: linear # in ["linear", "polynomial", "gaussian", "sigmoid"]
  gamma: auto # parameter for polynomial, gaussian and sigmoid
  degree: 2 # if polynomial, degree of the polynomial
  r: 0  # added constant for polynomial and sigmoid.
  args: {}


classifiers:
  classifier: svm # in ["svm", "logistic-regression"]
  args:
    C: 1
    solver: qp  # in ["qp", "sklearn"]