data:
  path: /path/to/data/folder/
  kfold: No  # If yes, does a 3-fold on the 3 datasets.
  merge: No  # if kfold is No, do we merge all 3 sets?
  only: 0  # if merge is No, which set to keep? Between 0 and 2.
  validation_set:  # if kfold is No...
    ratio: 0.1  # 10 percent of the total data

submissions:
  save: Yes  # If Yes, submissions and associated config file are saved at the given path.
  path: /path/to/submission/folder/

kernels:
  kernel: onehot # in ["onehot", "spectrum"]
  type: linear # in ["linear", "polynomial", "gaussian", "sigmoid"]
  gamma: auto # parameter for polynomial, gaussian and sigmoid
  degree: 2 # if polynomial, degree of the polynomial
  r: 0  # added constant for polynomial and sigmoid.
  args: {}


classifiers:
  classifier: svm # in ["svm", "logistic-regression"]
  args:
    C: 1
    solver: qp  # in ["qp", "sklearn"]