# Please copy this file
# Rename it {yourConfigName}.yaml
# Change the values
data:
  path: relative/path/to/data/folder/
  validation_set:  # if kfold is No...
    ratio: 0.1  # 10 percent of the total data

submissions:
  save: Yes  # If Yes, submissions and associated config file are saved at the given path.
  path: relative/path/to/submission/folder/

global:
  kernels:
    memoize:
      path: relative/path/to/memoized/data/
    coefs: [1, 0.5]
    kernels: # Gets a list of kernels to sum over
      - name: spectrum # in ["onehot", "spectrum", "mismatch", "substring", "local-alignment", "sum"]
        type: linear # in ["linear", "polynomial", "gaussian", "sigmoid"]
        gamma: auto # parameter for polynomial, gaussian and sigmoid
        degree: 2 # if polynomial, degree of the polynomial
        r: 0  # added constant for polynomial and sigmoid.
        normalize: Yes # If true, normalizes the gram matrix: K_norm(x, y) = K(x, y) / sqrt(K(x, x) K(y, y))
        args: {}

      - name: spectrum # in ["onehot", "spectrum", "mismatch", "substring", "local-alignment", "sum"]
        type: linear # in ["linear", "polynomial", "gaussian", "sigmoid"]
        gamma: auto # parameter for polynomial, gaussian and sigmoid
        degree: 2 # if polynomial, degree of the polynomial
        r: 0  # added constant for polynomial and sigmoid.
        normalize: Yes
        args: {}

  classifiers:
    classifier: svm # in ["svm", "logistic-regression"]
    args:
      C:
        gridsearch: {min: 0.5, max: 1.5, num: 5, type: linear}

# The default values are the one defined in global.
# Here are only the specific values for the 3 set which overrides the default.
# Gridsearch can be used here and is applied independently for each.
set0: {}

set1: {}

set2: {}

# Example changes for set0, this will only change kernels.args.length and classifiers.args.C.
#set0:
#  kernels:
#    args:
#      length: 3
#  classifiers:
#    args:
#      C: 2



# Gridsearch:
# instead of a value, add the keyword "gridsearch" and a list to do the gridsearch over
# gridsearch: [0, 1, 2]
# You can also specify
# {min: 0, max: 15, num: 10, type: linear}
# To create a np.linspace(0, 15, 10) or
# {min: 0, max: 5, num: 10, type: log}
# To create a np.logspace(0, 5, 10)
