data:
  path: /path/to/data/folder/

submissions:
  path: /path/to/submission/folder/

kernels:
  kernel: onehot # in ["onehot", "spectrum"]
  args: {}


classifiers:
  classifier: svm # in ["svm"]
  args:
    lbd: 0.1
    solver: qp  # in ["qp", "sklearn"]